name: user_list
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  dio: 5.4.3+1
  pretty_dio_logger: ^1.3.1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/

